### ISSUE TITLE
Why is send_synack_ack waiting for a response from the server? 

### ISSUE THREAD

**Issue by SivaDotRender** [violentshell/rover#3]
Why is the send_synack_ack function waiting for a response from the server? The server will not respond to a synack ack. The script gets stuck on my machine here: 

```
def send_synack_ack(self, pkt):
    print "something"
    logger.debug("Sent: ACK to SYN+ACK")
    self.l4[TCP].ack = pkt[TCP].seq + 1
    self.l4[TCP].flags = "A"
    self.seq_next = self.l4[TCP].seq
    print " send SYN ACK ack"
    response = sr1(self.l4, verbose=False) #no response received here
    self.alive = True
    print "SYN ACK ack"
    return self.handle_recv(response)
```

should it be `send()` instead of `sr1()` ?

**Comment by violentshell** [comment]
This is for ssh. SSH sends one more packet. If you like, replace the sr1() function
with send() and you should be fine.

**Comment by violentshell** [comment]
Correction, you still need to send the ack. OS replace the sr1() function
with send()

**Comment by SivaDotRender** [comment]
Right that makes sense! Thanks
