### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by nmapgithub** [violentshell/rover#6]
can u help mw with this :| 
![rover_err](https://cloud.githubusercontent.com/assets/19661493/18121216/f2a87066-6f7c-11e6-9d5c-7bb2e7c40742.PNG)

**Comment by violentshell** [comment]
It looks like you have a different version of scapy. What versions of python and or scapy are you running?

The line only silences some output, so you can comment it out by placing a '#' in front of the line if you like.

**Comment by nmapgithub** [comment]
python ver 2.7.11
scapy ver 2.2.0

**Comment by nmapgithub** [comment]
and bro my mouse got struk when i run it :]

**Comment by violentshell** [comment]
Update your scapy version and let me know how you go
